//go:build ignore

// gen converts the hand-drawn logo PNG into the pixel grid that
// internal/ui renders with half-block characters.
//
//	go run ./scripts/logo/gen.go website/static/img/skillshare-logo.png > internal/ui/logo_data.go
package main

import (
	"fmt"
	"image"
	_ "image/png"
	"os"
	"strings"
)

// size is the grid width and height in pixels; the terminal shows it as
// size columns by size/2 rows.
const size = 24

// alphaCutoff is the averaged alpha above which a cell counts as drawn.
const alphaCutoff = 110

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: go run ./scripts/logo/gen.go <logo.png>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fail(err)
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		fail(err)
	}

	x0, y0, x1, y1 := contentBounds(img)
	// Pad to a square so the logo keeps its proportions.
	if w, h := x1-x0, y1-y0; w > h {
		y0 -= (w - h) / 2
		y1 = y0 + w
	} else {
		x0 -= (h - w) / 2
		x1 = x0 + h
	}

	var b strings.Builder
	b.WriteString("// Code generated by scripts/logo/gen.go; DO NOT EDIT.\n\n")
	b.WriteString("package ui\n\n")
	b.WriteString("// logoPixels is the logo as rows of RRGGBB hex values; \"------\" is transparent.\n")
	b.WriteString("var logoPixels = []string{\n")
	for row := 0; row < size; row++ {
		b.WriteString("\t\"")
		for col := 0; col < size; col++ {
			r, g, bl, a := average(img, x0+col*(x1-x0)/size, x0+(col+1)*(x1-x0)/size, y0+row*(y1-y0)/size, y0+(row+1)*(y1-y0)/size)
			if a <= alphaCutoff {
				b.WriteString("------")
				continue
			}
			fmt.Fprintf(&b, "%02x%02x%02x", r, g, bl)
		}
		b.WriteString("\",\n")
	}
	b.WriteString("}\n")
	fmt.Print(b.String())
}

// contentBounds returns the bounding box of pixels that are mostly opaque.
func contentBounds(img image.Image) (x0, y0, x1, y1 int) {
	bounds := img.Bounds()
	x0, y0 = bounds.Max.X, bounds.Max.Y
	for y := bounds.Min.Y; y < bounds.Max.Y; y++ {
		for x := bounds.Min.X; x < bounds.Max.X; x++ {
			if _, _, _, a := img.At(x, y).RGBA(); a>>8 > 128 {
				x0, y0 = min(x0, x), min(y0, y)
				x1, y1 = max(x1, x+1), max(y1, y+1)
			}
		}
	}
	return x0, y0, x1, y1
}

// average returns the mean color of the opaque pixels in the box and the
// mean alpha of the whole box.
func average(img image.Image, sx0, sx1, sy0, sy1 int) (r, g, b, a uint64) {
	var n uint64
	for y := sy0; y < sy1; y++ {
		for x := sx0; x < sx1; x++ {
			cr, cg, cb, ca := img.At(x, y).RGBA()
			r += uint64(cr >> 8)
			g += uint64(cg >> 8)
			b += uint64(cb >> 8)
			a += uint64(ca >> 8)
			n++
		}
	}
	if n == 0 || a == 0 {
		return 0, 0, 0, 0
	}
	// RGBA() is alpha-premultiplied; divide by alpha to get the drawn color.
	r, g, b = min(r*255/a, 255), min(g*255/a, 255), min(b*255/a, 255)
	return r, g, b, a / n
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
